LOCATIONS = {{"@Pirate Ship Eleftheria2/PSE hold 2 chest 1/"},
{"@Pirate Ship Eleftheria2/PSE hold 3 chest 2/"},
{"@Pirate Ship Eleftheria2/PSE hold 2 chest 2/"},
{"@Pirate Ship Eleftheria2/PSE hold 3 chest 1/"},
{"@Pirate Ship Eleftheria2/PSE hold 1 chest 4/"},
{"@Pirate Ship Eleftheria1/PSE hold 1 chest 3/"},
{"@Pirate Ship Eleftheria1/PSE hold 1 chest 2/"},
{"@Pirate Ship Eleftheria1/PSE hold 1 chest 1/"},
{"@Pirate Ship Eleftheria1/PSE accessway chest 2/"},
{"@Pirate Ship Eleftheria1/PSE accessway chest 1/"},
{"@Pirate Ship Eleftheria1/PSE accessway chest 3/"},
{"@Pirate Ship Eleftheria1/PSE accessway chest 4/"},
{"@Pirate Ship Eleftheria1/PSE Crew Quarters chest 4/"},
{"@Pirate Ship Eleftheria1/PSE Crew Quarters chest 1/"},
{"@Pirate Ship Eleftheria1/PSE Crew Quarters chest 2/"},
{"@Pirate Ship Eleftheria1/PSE Crew Quarters chest 3/"},
{"@Pirate Ship Eleftheria1/PSE Crew Quarters chest 5/"},
{"@Pirate Ship Eleftheria2/Ship Deck/PSE Deck chest"},
{"@Pirate Ship Eleftheria2/PSE deckhouse chest 1/"},
{"@Pirate Ship Eleftheria2/PSE deckhouse chest 2/"},
{"@Pirate Ship Eleftheria2/PSE stairwell chest/"},
{"@Pirate Ship Eleftheria2/PSE deckhouse chest 3/"},
{"@Nameless Coast south/Nameless Coast chest 4/"},
{"@Nameless Coast south/Nameless Coast chest 2/"},
{"@Nameless Coast north/Nameless Coast chest 9/"},
{"@Nameless Coast north/Nameless Coast chest 10/"},
{"@Great River Valley northwest/GRV chest 11/"},
{"@Great River Valley/GRV chest 5/"},
{"@Beast Hills north/Beast Hills chest 1/"},
{"@Beast Hills south/Beast Hills chest 2/"},
{"@Beast Hills south/Beast Hills chest 3/"},
{"@Beast Hills south/Beast Hills chest 4/"},
{"@Nameless Coast south/Nameless Coast chest 3/"},
{"@Nameless Coast north/Nameless Coast chest 5/"},
{"@Nameless Coast north/Nameless Coast chest 6/"},
{"@White Sand Cape/WSC chest 1/"},
{"@Longhorn Coast/Longhorn Coast chest 1/"},
{"@Longhorn Coast/Longhorn Coast chest 2/"},
{"@Longhorn Coast/Longhorn Coast chest 3/"},
{"@Longhorn Coast/Longhorn Coast chest 4/"},
{"@Nostalgia Cape/Nostalgia Cape chest/"},
{"@Roaring Seashore beach/Metavolicalis/Roaring Seashore chest 2"},
{"@Roaring Seashore beach/Roaring Seashore chest 1/"},
{"@Great River Valley/GRV chest 3/"},
{"@Great River Valley/GRV chest 7/"},
{"@Great River Valley/GRV chest 6/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Solitude Island/Magnacarpa/Solitude chest"},
{"@Nameless Coast south/Nameless Coast chest 1/"},
{"@White Sand Cape/WSC chest 3/"},
{"@White Sand Cape/WSC chest 2/"},
{"@White Sand Cape/WSC chest 7/"},
{"@White Sand Cape/WSC chest 4/"},
{"@White Sand Cape/WSC chest 6/"},
{"@White Sand Cape/WSC chest 5/"},
{"@Roaring Seashore up/Roaring Seashore chest 3/"},
{"@Roaring Seashore up/Parasequoia/Roaring Seashore near Kong chest"},
{"@Towering Coral Forest1/TCF upper chest 1/"},
{"@Towering Coral Forest1/TCF upper chest 2/"},
{"@Towering Coral Forest Night/TCF Night upper chest 2/"},
{"@Towering Coral Forest Night/TCF Night upper chest 1/"},
{"@Towering Coral Forest Night/TCF Night upper chest 6/"},
{"@Towering Coral Forest1/TCF upper chest 8/"},
{"@Towering Coral Forest1/TCF upper chest 10/"},
{"@Towering Coral Forest1/TCF lower chest 2/"},
{"@Towering Coral Forest1/TCF upper chest 9/"},
{"@Towering Coral Forest Night/TCF Night upper chest 3/"},
{"@Towering Coral Forest Night/TCF Night upper chest 4/"},
{"@Towering Coral Forest Night/TCF Night lower chest 2/"},
{"@Towering Coral Forest Night/TCF Night lower chest 1/"},
{"@Towering Coral Forest Rainbow Falls/TCF upper chest 5/"},
{"@Towering Coral Forest Rainbow Falls/TCF upper chest 4/"},
{"@Towering Coral Forest Rainbow Falls/TCF upper chest 6/"},
{"@Towering Coral Forest Rainbow Falls/TCF upper chest 3/"},
{"@Towering Coral Forest Night/TCF Night upper chest 7/"},
{"@Towering Coral Forest Night/TCF Night upper chest 5/"},
{"@Towering Coral Forest Rainbow Falls/TCF upper chest 7/"},
{"@Towering Coral Forest2/TCF upper chest 12/"},
{"@Towering Coral Forest2/TCF upper chest 11/"},
{"@Towering Coral Forest2/TCF lower chest 3/"},
{"@Towering Coral Forest2/TCF lower chest 4/"},
{"@Towering Coral Forest Night/TCF Night upper chest 8/"},
{"@Towering Coral Forest Night/TCF Night upper chest 9/"},
{"@Towering Coral Forest Night/TCF Night lower chest 4/"},
{"@Towering Coral Forest1/TCF lower chest 1/"},
{"@Towering Coral Forest Night/TCF Night lower chest 3/"},
{"@Towering Coral Forest2/TCF upper chest 13/"},
{"@Towering Coral Forest Night/TCF Night upper chest 10/"},
{"@Nameless Coast north/Nameless Coast chest 7/"},
{"@Nameless Coast north/Nameless Coast chest 8/"},
{"@Great River Valley northwest/GRV chest 9/"},
{"@Great River Valley northwest/GRV chest 10/"},
{"@Great River Valley/GRV chest 2/"},
{"@Great River Valley/GRV chest 1/"},
{"@Great River Valley/GRV chest 4/"},
{"@Water and Wood Hills/WWH chest 2/"},
{"@Water and Wood Hills/WWH chest 3/"},
{"@Water and Wood Hills/WWH chest 1/"},
{"@Schlamm Jungle1/Jungle chest 1/"},
{"@Schlamm Jungle1/Jungle chest 2/"},
{"@Schlamm Jungle1/Jungle chest 5/"},
{"@Schlamm Jungle1/Jungle chest 3/"},
{"@Schlamm Jungle1/Mid-Boss Room/Jungle chest 4"},
{"@Schlamm Jungle2/Jungle chest 6/"},
{"@Schlamm Jungle2/Jungle chest 7/"},
{"@Field of Herbs area/Field of Herbs/Jungle chest 8"},
{"@Schlamm Jungle2/Jungle chest 9/"},
{"@Schlamm Jungle2/Jungle chest 10/"},
{"@Weathervane Hills/Weathervane Hills chest 2/"},
{"@Weathervane Hills/Weathervane Hills chest 1/"},
{"@Weathervane Hills/Weathervane Hills chest 3/"},
{"@Great River Valley/GRV chest 8/"},
{"@Great River Valley/GRV near Beast Hills chest/"},
{"@West Foot of Gendarme/WFoG chest 1/"},
{"@West Foot of Gendarme/Cairn/WFoG chest 2"},
{"@Primordial Passage/Primordial Passage chest 1/"},
{"@Primordial Passage/Primordial Passage chest 2/"},
{"@Mountain Pinnacle Trail/MPT upper chest/"},
{"@Mountain Pinnacle Trail/MPT lower lvl chest 2/"},
{"@Mountain Pinnacle Trail/MPT lower lvl chest 1/"},
{"@Mountain Pinnacle Trail/MPT lower lvl chest 3/"},
{"@Mountain Pinnacle Trail/MPT lower lvl chest 4/"},
{"@Mountain Pinnacle Trail/MPT lower lvl chest 5/"},
{"@Vista Ridge/Top/Vista Ridge chest 2"},
{"@Vista Ridge/Vista Ridge chest 1/"},
{"@Eroded Valley1/Eroded Valley chest 1/"},
{"@Eroded Valley1/Eroded Valley chest 2/"},
{"@Eroded Valley2/Eroded Valley chest 12/"},
{"@Eroded Valley1/Eroded Valley chest 5/"},
{"@Eroded Valley2/Eroded Valley chest 11/"},
{"@Eroded Valley1/Eroded Valley chest 4/"},
{"@Eroded Valley1/Eroded Valley chest 3/"},
{"@Eroded Valley1/Eroded Valley chest 6/"},
{"@Eroded Valley1/Eroded Valley chest 17/"},
{"@Eroded Valley1/Eroded Valley chest 7/"},
{"@Eroded Valley1/Eroded Valley chest 9/"},
{"@Eroded Valley1/Eroded Valley chest 8/"},
{"@Eroded Valley1/Mid-Boss Room/Eroded Valley chest 10"},
{"@Eroded Valley2/Eroded Valley chest 13/"},
{"@Eroded Valley2/Eroded Valley chest 14/"},
{"@Eroded Valley2/Eroded Valley chest 15/"},
{"@Eroded Valley2/Eroded Valley chest 16/"},
{"@Mt Gendarme1/Mt Gendarme bottom chest 1/"},
{"@Mt Gendarme Night/Mt Gendarme Night bottom chest/"},
{"@Mt Gendarme1/Mt Gendarme mid chest 2/"},
{"@Mt Gendarme1/Mt Gendarme mid chest 1/"},
{"@Mt Gendarme Night/Mt Gendarme Night mid chest 1/"},
{"@Mt Gendarme Night/Mt Gendarme Night mid chest 2/"},
{"@Mt Gendarme Night/Mt Gendarme Night mid chest 5/"},
{"@Mt Gendarme1/Mt Gendarme mid chest 4/"},
{"@Mt Gendarme1/Mt Gendarme mid chest 3/"},
{"@Mt Gendarme1/Mt Gendarme mid chest 5/"},
{"@Mt Gendarme Night/Mt Gendarme Night mid chest 3/"},
{"@Mt Gendarme Night/Mt Gendarme Night mid chest 4/"},
{"@Mt Gendarme1/Mt Gendarme mid chest 8/"},
{"@Mt Gendarme1/Mt Gendarme mid chest 6/"},
{"@Mt Gendarme1/Mt Gendarme mid chest 7/"},
{"@Mt Gendarme Night/Mt Gendarme Night mid chest 6/"},
{"@Mt Gendarme Night/Mt Gendarme Night mid chest 7/"},
{"@Mt Gendarme2/Mt Gendarme upper 1 chest 1/"},
{"@Mt Gendarme2/Mt Gendarme upper 1 chest 2/"},
{"@Mt Gendarme Night/Mt Gendarme Night upper 1 chest/"},
{"@Mt Gendarme2/Mt Gendarme upper 2 chest/"},
{"@Mt Gendarme Night/Mt Gendarme Night upper 2 chest/"},
{"@Titis Primeval Forest/TPF chest 5/"},
{"@Titis Primeval Forest/TPF chest 2/"},
{"@Titis Primeval Forest/TPF chest 3/"},
{"@Titis Primeval Forest/TPF chest 4/"},
{"@Titis Primeval Forest/TPF chest 1/"},
{"@Towal Highway/Towal Highway chest 2/"},
{"@Lodinia Marshland 1st half/Lodinia Marshland chest 1/"},
{"@Lodinia Marshland 1st half/Lodinia Marshland chest 3/"},
{"@Lodinia Marshland 1st half/Lodinia Marshland chest 2/"},
{"@Lodinia Marshland 2nd half/Lodinia Marshland chest 7/"},
{"@Lodinia Marshland 2nd half/Lodinia Marshland chest 8/"},
{"@Valley of Kings Entrance/Valley of Kings chest/"},
{"@Blank/Blank/"},
{"@Eternal Hill/Eternal Hill chest/"},
{"@Pangaia Plains/Pangaia Plains chest 3/"},
{"@Pangaia Plains Night/Pangaia Plains Night chest 2/"},
{"@Pangaia Plains/Ancient Tree/Pangaia Plains chest 4"},
{"@Pangaia Plains Night/Pangaia Plains Night chest 1/"},
{"@Lodinia Marshland 1st half/Lodinia Marshland chest 4/"},
{"@Lodinia Marshland 1st half/Lodinia Marshland chest 5/"},
{"@Lodinia Marshland 1st half/Lodinia Marshland chest 6/"},
{"@Lodinia Marshland 2nd half/Lodinia Marshland chest 9/"},
{"@Lodinia Marshland 2nd half/Lodinia Marshland chest 11/"},
{"@Lodinia Marshland 2nd half/Lodinia Marshland chest 10/"},
{"@Towal Highway/Towal Highway chest 1/"},
{"@Pangaia Plains/Pangaia Plains chest 1/"},
{"@Pangaia Plains/Pangaia Plains chest 2/"},
{"@Pangaia Plains Night/Pangaia Plains Night chest 3/"},
{"@Ruins of Eternia/Ruins of Eternia chest 3/"},
{"@Ruins of Eternia/Ruins of Eternia chest 4/"},
{"@Ruins of Eternia/Locked Room/Ruins of Eternia chest 5"},
{"@Ruins of Eternia/Locked Room/Ruins of Eternia chest 6"},
{"@Ruins of Eternia/Locked Room/Ruins of Eternia chest 7"},
{"@Ruins of Eternia/House near Monastery/Ruins of Eternia chest 2"},
{"@Ruins of Eternia/House near Monastery/Ruins of Eternia chest 1"},
{"@Octus: Ocean Path/Ocean Path Chest 1"},
{"@Octus: Ocean Path/Ocean Path Chest 2"},
{"@Octus: Frozen Path/Frozen Path Chest 1"},
{"@Octus: Frozen Path/Frozen Path Chest 2"},
{"@Octus: Frozen Path/Frozen Path Chest 3"},
{"@Octus: Insectoid Path/Insectoid Path Chest 2"},
{"@Octus: Insectoid Path/Insectoid Path Chest 1"},
{"@Octus: Insectoid Path/Insectoid Path Chest 3"},
{"@Octus: Sky Path/Sky Path Chest 1"},
{"@Octus: Sky Path/Sky Path Chest 2"},
{"@Octus: Sky Path/Sky Path Chest 3"},
{"@Selection Sphere/Selection Sphere Chest 1"},
{"@Selection Sphere/Selection Sphere Chest 2"},
{"@Selection Sphere/Selection Sphere Chest 3"},
{"@Baja Tower1/Baja Tower 2-2 chest 3/"},
{"@Baja Tower1/Baja Tower 2-2 chest 2/"},
{"@Baja Tower1/Baja Tower 2-2 chest 1/"},
{"@Baja Tower1/Baja Tower 3 chest 3/"},
{"@Baja Tower1/Baja Tower 3 chest 2/"},
{"@Baja Tower1/Baja Tower 3 chest 4/"},
{"@Baja Tower1/Baja Tower 3 chest 1/"},
{"@Baja Tower1/Baja Tower Hallway 1-2 chest/"},
{"@Baja Tower2/Baja Tower 5-1 chest/"},
{"@Baja Tower2/Baja Tower 5-2 chest/"},
{"@Baja Tower2/Baja Tower 6 chest 3/"},
{"@Baja Tower2/Baja Tower 6 chest 1/"},
{"@Baja Tower2/Baja Tower 6 chest 2/"},
{"@Baja Tower2/Baja Tower 6 chest 5/"},
{"@Baja Tower2/Baja Tower 6 chest 4/"},
{"@Valley of Kings1/VoK upper lvl chest 1/"},
{"@Valley of Kings1/VoK upper lvl chest 2/"},
{"@Valley of Kings1/VoK upper lvl chest 3/"},
{"@Valley of Kings1/VoK lower lvl chest 3/"},
{"@Valley of Kings1/VoK depths chest 1/"},
{"@Valley of Kings1/VoK depths chest 2/"},
{"@Valley of Kings1/VoK lower lvl chest 2/"},
{"@Valley of Kings1/VoK lower lvl chest 1/"},
{"@Valley of Kings1/VoK upper lvl chest 4/"},
{"@Valley of Kings2/VoK lower lvl chest 4/"},
{"@Valley of Kings2/VoK lower lvl chest 5/"},
{"@Valley of Kings2/VoK lower lvl chest 6/"},
{"@Valley of Kings2/VoK lower lvl chest 7/"},
{"@Valley of Kings2/VoK lower lvl chest 9/"},
{"@Valley of Kings2/VoK lower lvl chest 11/"},
{"@Valley of Kings2/VoK lower lvl chest 10/"},
{"@Valley of Kings2/VoK lower lvl chest 8/"},
{"@Archeozoic Chasm1/Archeozoic Chasm bottom chest 1/"},
{"@Archeozoic Chasm1/Archeozoic Chasm mid chest 1/"},
{"@Archeozoic Chasm1/Archeozoic Chasm mid chest 2/"},
{"@Archeozoic Chasm1/Archeozoic Chasm bottom chest 3/"},
{"@Archeozoic Chasm1/Archeozoic Chasm bottom chest 2/"},
{"@Archeozoic Chasm1/Archeozoic Chasm bottom chest 4/"},
{"@Archeozoic Chasm2/Archeozoic Chasm bottom chest 5/"},
{"@Archeozoic Chasm2/Archeozoic Chasm bottom chest 6/"},
{"@Archeozoic Chasm2/Archeozoic Chasm bottom chest 7/"},
{"@Archeozoic Chasm2/Archeozoic Chasm bottom chest 8/"},
{"@Archeozoic Chasm2/Archeozoic Chasm bottom chest 9/"},
{"@Archeozoic Chasm2/Archeozoic Chasm bottom chest 10/"},
{"@Archeozoic Chasm2/Archeozoic Chasm bottom chest 12/"},
{"@Archeozoic Chasm2/Archeozoic Chasm bottom chest 11/"},
{"@Silent Tower/Silent Tower passage 1 chest/"},
{"@Silent Tower/Silent Tower B1F chest 1/"},
{"@Silent Tower/Silent Tower B1F chest 2/"},
{"@Silent Tower/Silent Tower passage 2 chest/"},
{"@Silent Tower/Silent Tower B2F chest 1/"},
{"@Silent Tower/Silent Tower B2F chest 2/"},
{"@Silent Tower/Mephorash/Silent Tower B2F chest 3"},
{"@Bolado Monastery/Behind 1F Grid/Bolado Monastery 1F chest 2"},
{"@Bolado Monastery/Behind 1F Grid/Bolado Monastery 1F chest 1"},
{"@Bolado Monastery/Behind 1F Grid/Bolado Monastery 1F chest 3"},
{"@Bolado Monastery/Bolado Monastery 2F chest 1/"},
{"@Bolado Monastery/Bolado Monastery 2F chest 2/"},
{"@Bolado Monastery/Behind Basement Grid/Bolado Monastery B1F chest 4"},
{"@Bolado Monastery/Behind Basement Grid/Bolado Monastery B1F chest 5"},
{"@Bolado Monastery/Behind Basement Grid/Bolado Monastery B1F chest 3"},
{"@Bolado Monastery/Bolado Monastery B1F chest 1/"},
{"@Bolado Monastery/Bolado Monastery B1F chest 2/"},
{"@Ancient Sanctuary Crypt F1/ASC F1 chest 1/"},
{"@Ancient Sanctuary Crypt F1/ASC F1 chest 3/"},
{"@Ancient Sanctuary Crypt F1/ASC F1 chest 2/"},
{"@Blank/Blank/"},
{"@Ancient Sanctuary Crypt F1/ASC F1 chest 7/"},
{"@Ancient Sanctuary Crypt F1/ASC F1 chest 4/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Ancient Sanctuary Crypt F1/ASC F1 chest 5/"},
{"@Ancient Sanctuary Crypt F1/ASC F1 chest 6/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Ancient Sanctuary Crypt F1/ASC F1 chest 8/"},
{"@Blank/Blank/"},
{"@Ancient Sanctuary Crypt F2/ASC F2 chest 3/"},
{"@Ancient Sanctuary Crypt F2/ASC F2 chest 2/"},
{"@Ancient Sanctuary Crypt F2/ASC F2 chest 1/"},
{"@Ancient Sanctuary Crypt F2/ASC F2 chest 4/"},
{"@Ancient Sanctuary Crypt F2/ASC F2 chest 5/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Ancient Sanctuary Crypt F2/ASC F2 chest 6/"},
{"@Blank/Blank/"},
{"@Ancient Sanctuary Crypt F3/ASC F3 upper chest 1/"},
{"@Ancient Sanctuary Crypt F3/ASC F3 upper chest 2/"},
{"@Ancient Sanctuary Crypt F3/ASC F3 upper chest 4/"},
{"@Ancient Sanctuary Crypt F3/ASC F3 upper chest 7/"},
{"@Ancient Sanctuary Crypt F3/ASC F3 upper chest 3/"},
{"@Ancient Sanctuary Crypt F3/ASC F3 upper chest 6/"},
{"@Ancient Sanctuary Crypt F3/ASC F3 upper chest 5/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Ancient Sanctuary Crypt F3/ASC F3 upper chest 8/"},
{"@Ancient Sanctuary Crypt F3/ASC F3 lower chest 1/"},
{"@Ancient Sanctuary Crypt F3/ASC F3 lower chest 2/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Ancient Sanctuary Crypt F3/ASC F3 lower chest 3/"},
{"@Blank/Blank/"},
{"@Ancient Sanctuary Crypt F4/ASC F4 chest 1/"},
{"@Ancient Sanctuary Crypt F4/ASC F4 chest 4/"},
{"@Ancient Sanctuary Crypt F4/ASC F4 chest 2/"},
{"@Ancient Sanctuary Crypt F4/ASC F4 chest 3/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Ancient Sanctuary Crypt F4/ASC F4 chest 5/"},
{"@Ancient Sanctuary Crypt F4/ASC F4 chest 6/"},
{"@Ancient Sanctuary Crypt F4/ASC F4 chest 8/"},
{"@Ancient Sanctuary Crypt F4/ASC F4 chest 7/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Ancient Sanctuary Crypt F4/ASC F4 chest 9/"},
{"@Blank/Blank/"},
{"@Ancient Sanctuary Crypt F5/ASC F5 chest 1/"},
{"@Ancient Sanctuary Crypt F5/ASC F5 chest 2/"},
{"@Ancient Sanctuary Crypt F5/ASC F5 chest 3/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Ancient Sanctuary Crypt F5/ASC F5 chest 4/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Ancient Sanctuary Crypt F5/ASC F5 chest 5/"},
{"@Ancient Sanctuary Crypt F5/ASC F5 chest 6/"},
{"@Ancient Sanctuary Crypt F5/ASC F5 chest 8/"},
{"@Ancient Sanctuary Crypt F5/ASC F5 chest 7/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Ancient Sanctuary Crypt F5/ASC F5 chest 9/"},
{"@Ancient Sanctuary Crypt F5/ASC F5 chest 10/"},
{"@Ancient Sanctuary Crypt F5/ASC F5 chest 11/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Ancient Sanctuary Crypt Final Layer/ASC final layer near elevator/ASC final layer chest 3"},
{"@Ancient Sanctuary Crypt Final Layer/ASC final layer near elevator/ASC final layer chest 2"},
{"@Ancient Sanctuary Crypt Final Layer/ASC final layer near elevator/ASC final layer chest 1"},
{"@Ancient Sanctuary Crypt Final Layer/ASC final layer chest 4/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Mountain Pinnacle Trail/MPT Cave 1 chest/"},
{"@Waterdrop Cave/Waterdrop chest 2/"},
{"@Waterdrop Cave/Waterdrop chest 1/"},
{"@Waterdrop Cave/Waterdrop chest 3/"},
{"@East Coast Cave/East Coast Cave chest 3/"},
{"@East Coast Cave/Pirate Storehouse/East Coast Cave chest 1"},
{"@East Coast Cave/East Coast Cave chest 2/"},
{"@Headwater Falls/Headwater Falls chest 1/"},
{"@Headwater Falls/Headwater Falls chest 4/"},
{"@Headwater Falls/Headwater Falls chest 5/"},
{"@Headwater Falls/Headwater Falls chest 2/"},
{"@Headwater Falls/Headwater Falls chest 3/"},
{"@Underground Water Vein/UWV bottom chest/"},
{"@Underground Water Vein/Alcove/UWV chest 2"},
{"@Underground Water Vein/UWV chest 1/"},
{"@Waterfall Grotto/Waterfall Grotto chest 1/"},
{"@Waterfall Grotto/Waterfall Grotto chest 2/"},
{"@Submerged Cemetery/Soundless Hall/Submerged Cemetery chest 2"},
{"@Submerged Cemetery/Submerged Cemetery chest 1/"},
{"@Stone Pillar Wind Cave/SPWC chest 1/"},
{"@Stone Pillar Wind Cave/SPWC chest 3/"},
{"@Stone Pillar Wind Cave/SPWC chest 4/"},
{"@Stone Pillar Wind Cave/SPWC chest 5/"},
{"@Stone Pillar Wind Cave/SPWC chest 2/"},
{"@Nameless Coast south/Laxia Join/"},
{"@Waterdrop Cave/Byfteriza Boss Fight/Captain Barbaros Join"},
{"@Calm Inlet/After Avalodragil/Little Paro Join"},
{"@Nameless Coast south/Bosses/Sahad Join"},
{"@Calm Inlet/After Avalodragil/Dogi Join"},
{"@White Sand Cape/Find Alison/"},
{"@Towering Coral Forest1/Find Castaways/Sir Carlan Join"},
{"@Towering Coral Forest1/Find Castaways/Kiergaard Join"},
{"@Roaring Seashore beach/Find Kathleen/"},
{"@Waterfall Grotto/Find Sister Nia/"},
{"@Beast Hills north/Hummel/"},
{"@Sunrise Beach/Find Dina"},
{"@Longhorn Coast/Reja Join/"},
{"@Schlamm Jungle1/Euron finds you/"},
{"@Odd Rock Coast/Find Licht"},
{"@Nameless Coast south/Bosses/Quina Join"},
{"@Mt Gendarme1/Avalodragil Second Fight/Ricotta Join"},
{"@West Foot of Gendarme/Save Austin from wolves/"},
{"@Water and Wood Hills/Miralda Join/"},
{"@Temple of the Great Tree/Thanatos Join"},
{"@Pangaia Plains/Breath Fountain/Find Silvia"},
{"@Temple of the Great Tree/Dana Join"},
{"@Towal Highway/Find Katthew/"},
{"@Nostalgia Cape/Find Ed/"},
{"@Vista Ridge/Top/Find Franz"},
{"@Calm Inlet/Shoebill Join/"},
{"@Eternal Hill/Grave/Find Griselda"},
{"@Master Kong Trainings/Vista Ridge training/Master Kong Join"},
{"@Blank/Blank/"},
{"@Towering Coral Forest1/Grip Gloves on corpse/"},
{"@West Foot of Gendarme/Orichalcum Ore in cave/"},
{"@Valley of Kings2/Mistilteinn cutscene/"},
{"@Temple of the Great Tree/Dana's Flame Stone"},
{"@Pirate Ship Eleftheria2/Ship Deck/Pirate Revenant Boss Fight"},
{"@Eroded Valley2/Gargantula Boss Fight/Kill it with fire"},
{"@Valley of Kings2/Basileus Boss Fight/Kill Basileus"},
{"@Archeozoic Chasm2/Final Room/Oceanus Boss Fight"},
{"@Blank/Blank/"},
{"@Temple of the Great Tree/Pot in Dana's room"},
{"@Baja Tower2/Top of the Tower/Study history after boss"},
{"@Solitude Island/Find Big Pikkard/"},
{"@Underground Water Vein/Alcove/UWV pikkard"},
{"@Mt Gendarme1/Wish tree/"},
{"@Longhorn Coast/Beehive/Check under stone"},
{"@Lodinia Marshland 2nd half/Top/Climb for tree sap"},
{"@Dogi's interceptions/Agents of the Sea"},
{"@Dogi's interceptions/Tyrant's Invading Army"},
{"@Dogi's interceptions/Agents of the Deep Sea"},
{"@Dogi's interceptions/Creeping Beasts of Yore"},
{"@Dogi's interceptions/Wisened Onslaught"},
{"@Calm Inlet/Exploration/10 Exploration"},
{"@Calm Inlet/Exploration/20 Exploration"},
{"@Calm Inlet/Exploration/30 Exploration"},
{"@Calm Inlet/Exploration/40 Exploration"},
{"@Calm Inlet/Exploration/50 Exploration"},
{"@Calm Inlet/Exploration/60 Exploration"},
{"@Calm Inlet/Exploration/70 Exploration"},
{"@Calm Inlet/Exploration/80 Exploration"},
{"@Calm Inlet/Exploration/90 Exploration"},
{"@Calm Inlet/Exploration/100 Exploration"},
{"@Dina Trades/Dina trade 1"},
{"@Dina Trades/Dina trade 2"},
{"@Dina Trades/Dina trade 3"},
{"@Dina Trades/Dina trade 4"},
{"@Dina Trades/Dina trade 5"},
{"@Dina Trades/Dina trade 6"},
{"@Dina Trades/Dina trade 7"},
{"@Dina Trades/Dina trade 8"},
{"@Dina Trades/Dina trade 9"},
{"@Dina Trades/Dina trade 10"},
{"@Calm Inlet/After Avalodragil/Fishing tutorial"},
{"@Fish trades/Fish trade 1"},
{"@Fish trades/Fish trade 2"},
{"@Fish trades/Fish trade 3"},
{"@Fish trades/Fish trade 4"},
{"@Fish trades/Fish trade 5"},
{"@Fish trades/Fish trade 6"},
{"@Calm Inlet/Discoveries/12 Discoveries shown"},
{"@Calm Inlet/Discoveries/24 Discoveries shown"},
{"@Food trades/Food trade 1"},
{"@Food trades/Food trade 2"},
{"@Food trades/Food trade 3"},
{"@Food trades/Food trade 4"},
{"@Food trades/Food trade 5"},
{"@Food trades/Food trade 6"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Waterdrop Cave/Waterdrop pirate corpse/"},
{"@Eroded Valley2/Eroded Valley Pirate Corpse 3/"},
{"@Eroded Valley1/Eroded Valley Pirate Corpse 2/"},
{"@Eroded Valley1/Eroded Valley Pirate Corpse 1/"},
{"@Schlamm Jungle1/Jungle Pirate Corpse/"},
{"@Longhorn Coast/Longhorn Coast Pirate Corpse/"},
{"@Pirate Ship Eleftheria2/PSE deckhouse Pirate Corpse/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Longhorn Coast/Reja's Pikkard/"},
{"@Ruins of Eternia/Thanatos spooks you/"},
{"@Pirate Ship Eleftheria2/Ship Deck/Seiren Chart"},
{"@Nostalgia Cape/Wreckage/Nostalgia Cape item in crate"},
{"@Solitude Island/Solitude freestanding item/"},
{"@Pirate Ship Eleftheria1/PSE hold 1 Pirate Corpse/"},
{"@Archeozoic Chasm2/Final Room/Lombardia Nameplate"},
{"@Underground Water Vein/UWV item on the ground/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Silent Tower/Mephorash/Mephorash Skill"},
{"@Ancient Sanctuary Crypt Final Layer/Melaiduma Boss Fight/"},
{"@Octus: Sky Path/Psyche Ura's Skill 1"},
{"@Octus: Sky Path/Psyche Ura's Skill 2"},
{"@Octus: Insectoid Path/Psyche Nestor's Skill 1"},
{"@Octus: Insectoid Path/Psyche Nestor's Skill 2"},
{"@Octus: Frozen Path/Psyche Minos' Skill 1"},
{"@Octus: Frozen Path/Psyche Minos' Skill 2"},
{"@Octus: Ocean Path/Psyche Hydra's Skill 1"},
{"@Octus: Ocean Path/Psyche Hydra's Skill 2"},
{"@Calm Inlet/Fight Silvia/Silvia's Skill 1"},
{"@Calm Inlet/Fight Silvia/Silvia's Skill 2"},
{"@Valley of Kings2/Basileus Boss Fight/Basileus Skill 1"},
{"@Valley of Kings2/Basileus Boss Fight/Basileus Skill 2"},
{"@Valley of Kings1/Doxa Griel Boss Fight/Doxa Griel's Skill 1"},
{"@Valley of Kings1/Doxa Griel Boss Fight/Doxa Griel's Skill 2"},
{"@Archeozoic Chasm2/Final Room/Oceanus' Skill 1"},
{"@Archeozoic Chasm2/Final Room/Oceanus' Skill 2"},
{"@Archeozoic Chasm1/Coelacantos Boss Fight/Coelacantos' Skill 1"},
{"@Archeozoic Chasm1/Coelacantos Boss Fight/Coelacantos' Skill 2"},
{"@Pirate Ship Eleftheria2/Ship Deck/Pirate Revenant's Skill 1"},
{"@Pirate Ship Eleftheria2/Ship Deck/Pirate Revenant's Skill 2"},
{"@Baja Tower2/Top of the Tower/Carveros' Skill 1"},
{"@Baja Tower2/Top of the Tower/Carveros' Skill 2"},
{"@Baja Tower1/Exmetal Boss Fight/Exmetal's Skill 1"},
{"@Baja Tower1/Exmetal Boss Fight/Exmetal's Skill 2"},
{"@Temple of the Great Tree/Brachion's Skill 1"},
{"@Temple of the Great Tree/Brachion's Skill 2"},
{"@Mt Gendarme2/Giasburn Boss Fight/Giasburn's Skill 1"},
{"@Mt Gendarme2/Giasburn Boss Fight/Giasburn's Skill 2"},
{"@Mt Gendarme1/Avalodragil Second Fight/Avalodragil 2 Skill 1"},
{"@Mt Gendarme1/Avalodragil Second Fight/Avalodragil 2 Skill 2"},
{"@Nameless Coast south/Bosses/Nameless Ripper's Skill 1"},
{"@Nameless Coast south/Bosses/Nameless Ripper's Skill 2"},
{"@Schlamm Jungle2/Laspisus Boss Fight/Laspisus' Skill 1"},
{"@Schlamm Jungle2/Laspisus Boss Fight/Laspisus' Skill 2"},
{"@Schlamm Jungle1/Mid-Boss Room/Magamandra's Skill 1"},
{"@Schlamm Jungle1/Mid-Boss Room/Magamandra's Skill 2"},
{"@Eroded Valley2/Gargantula Boss Fight/Gargantula Skill 1"},
{"@Eroded Valley2/Gargantula Boss Fight/Gargantula Skill 2"},
{"@Eroded Valley1/Mid-Boss Room/Lombrigius' Skill 1"},
{"@Eroded Valley1/Mid-Boss Room/Lombrigius' Skill 2"},
{"@Towering Coral Forest2/Clareon Boss Fight/Clareon's Skill 1"},
{"@Towering Coral Forest2/Clareon Boss Fight/Clareon's Skill 2"},
{"@Towering Coral Forest1/Serpentus Boss Fight/Serpentus' Skill 1"},
{"@Towering Coral Forest1/Serpentus Boss Fight/Serpentus' Skill 2"},
{"@Nameless Coast south/Bosses/Avalodragil Skill"},
{"@Waterdrop Cave/Byfteriza Boss Fight/Byfteriza Skill"},
{"@Master Kong Trainings/Roaring Seashore training/"},
{"@Master Kong Trainings/Sunrise Beach training/"},
{"@Master Kong Trainings/Odd Rock Coast training/"},
{"@Master Kong Trainings/Mt Gendarme summit training/"},
{"@Master Kong Trainings/Pangaia Plains training/"},
{"@Master Kong Trainings/Vista Ridge training/Adol Training"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Blank/Blank/"},
{"@Ancient Sanctuary Crypt Final Layer/Ancient Sanctuary Crypt final chest/"},
{"@Ruins of Eternia/Bird statue in the stupa/"},
{"@Blank/Blank/"},
{"@Nameless Coast north/Birdsong Rock Discovery/"},
{"@White Sand Cape/Cobalt Crag Discovery/"},
{"@Towering Coral Forest Rainbow Falls/Rainbow Falls Discovery/"},
{"@Roaring Seashore beach/Metavolicalis/Metavolicalis Discovery"},
{"@Roaring Seashore up/Parasequoia/Parasequoia Discovery"},
{"@Great River Valley/Chimney Rock Discovery/"},
{"@Eroded Valley1/Indigo Mineral Vein Discovery/"},
{"@Sunrise Beach/Beached Remains Discovery"},
{"@Field of Herbs area/Field of Herbs/Field of Medicinal Herbs Discovery"},
{"@West Foot of Gendarme/Cairn/Airs Cairn Discovery"},
{"@Weathervane Hills/Zephyr Hill Discovery/"},
{"@Underground Water Vein/Lapis Mineral Vein Discovery/"},
{"@Longhorn Coast/Beehive/Beehive Discovery"},
{"@Nostalgia Cape/Wreckage/Ship Graveyard Discovery"},
{"@East Coast Cave/Pirate Storehouse/Hidden Pirate's Storehouse"},
{"@Solitude Island/Magnacarpa/Magnacarpa Discovery"},
{"@Mountain Pinnacle Trail/Prismatic Mineral Vein Discovery/"},
{"@Titis Primeval Forest/Unicalamites Discovery/"},
{"@Pangaia Plains/Breath Fountain/Breath Fountain Discovery"},
{"@Pangaia Plains/Ancient Tree/Ancient Tree Discovery"},
{"@Lodinia Marshland 2nd half/Top/Sky Garden Discovery"},
{"@Submerged Cemetery/Soundless Hall/Soundless Hall Discovery"},
{"@Eternal Hill/Grave/Grave of Ancient Heroes Discovery"},
{"@Waterfall Grotto/Milky White Vein Discovery/"},



}





LOCATION_MAPPING = {
}
for n, item in ipairs(LOCATIONS) do
    LOCATION_MAPPING[n] = item
end